### ISSUE TITLE
stuck with introcuctory message

### ISSUE THREAD

**Issue by karl616** [jefferyto/gedit-ex-mortis#2]
After following the installation instructions I'm stuck with the blue banner stating that "This window cannot be reopened if closed. Restart gedit to fully enable Ex-Mortis ..." It does not seem to matter how many times I restart gedit.

Is there an easy way to debug this?

**Comment by jefferyto** [comment]
Hmm... what OS / gedit version are you using?

**Comment by karl616** [comment]
Just updated to fedora 28 and it comes with gedit 3.28.1
I didn't use ex-mortis before, but closing all my tabs for the update made me want it installed...

**Comment by jefferyto** [comment]
I'll see if I can reproduce it in a VM.

**Comment by karl616** [comment]
I'm not on top of how ex-mortis works, but I had to create the plugin folder. How is the list of files stored between sessions? Could it be as simple as a missing folder?

I hope it is reproducible, but am afraid it isn't. My installation has jumped from release to release several times.

**Comment by jefferyto** [comment]
It's stored in gsettings (in /com/thingsthemselves/gedit/plugins/ex-mortis), you can view the settings using dconf-editor.

**Comment by karl616** [comment]
It is there.

restore-windows is a string array. As long as gedit runs it contains 'window0'. This seems independent on the number of files I have open. When gedit closes or I toogle restore-between-sessions it becomes empty.

**Comment by jefferyto** [comment]
I haven't been able to reproduce this issue yet... Do you have any other gedit plugins installed/activated?

**Comment by karl616** [comment]
I do. This is my first third-party plugin though. Here is a list:
Code comment
Commander
Dashboard
Document Statistics
File Browser Panel
Insert Date/Time
Modelines
Spell Checker
Word Completion

When locking into the log trying to understand this problem I think Dashboard was also acting up. I will try to disable it.

**Comment by karl616** [comment]
That's it.
I disabled all plugins I rarely use and then Ex-mortis works. Here are those I kept

Code Comment
Document Statistics
Spell Checker
Word Completion

**Comment by karl616** [comment]
Reactivating Dashboard makes the error come back

**Comment by jefferyto** [comment]
I see... I'll look into how the two plugins are conflicting.

**Comment by jefferyto** [comment]
It appears the Dashboard plugin hasn't been updated to work with the 3.12 redesign. (I get [this error](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881395) when I open a new tab, and I don't see any dashboard-like functionality.)

Rather than try to get Ex-Mortis working with the Dashboard plugin as it is, I think it would be better to add a note to the readme, letting others know of the conflict and to disable the Dashboard plugin. I can revisit this issue if the Dashboard plugin is updated to work with current versions of gedit. (If the Dashboard plugin works for you now, please let me know.)

Thanks for filing this issue and investigating :smile:

**Comment by karl616** [comment]
For what it's worth, I completely agree. The presence of the Dashboard plugin was leftovers from before... No tears shed disabling it...
Thanks for the help

**Comment by netzgestaltung** [comment]
just for instance - the dashboard plugin doesnt have been updated since then.

**Comment by kueblc** [comment]
I'm experiencing this issue and I do not have `dashboard` enabled. Any other plugins known to have incompatibility?

Interestingly, it only happens when I launch gedit from the gnome-shell dash. My tabs are restored correctly when launching gedit from terminal.

**Comment by kueblc** [comment]
Narrowed it down to incompatibility with the `zeitgeist` plugin, in my case.

**Comment by jefferyto** [comment]
@kueblc Does the zeitgeist plugin still work? (Or necessary? I thought GNOME Shell just tracks everything :joy:) Aside from [some repo-wide cleanup](https://gitlab.gnome.org/GNOME/gedit-plugins/commits/master/plugins/zeitgeist) it doesn't appear to have been updated since 2015.

I'll try to find some time to test it soon, but I can't make any promises.

**Comment by kueblc** [comment]
To be honest I'm not sure if it still works or if it's necessary. I figured I needed `ex-mortis` more than `zeitgeist` anyway so my case is resolved, but for posterity I'm letting others know if they end up with the same problem.

Thanks for your efforts, truly appreciated.

**Comment by jefferyto** [comment]
@kueblc Thanks for your report - I've updated the readme :smile:

I still plan on looking into zeitgeist (and now dashboard as well). If there are defensive things ex-mortis can do to avoid conflicts then it should do so.
